home_url = "http://localhost:4200/home"
register_url = "http://localhost:4200/users"
login_url = "http://localhost:4200/user"
cart_url = "http://localhost:4200/cart"
profile_url = "http://localhost:4200/profile"
orders_url = "http://localhost:4200/order"
payment_url = "http://localhost:4200/payment"
front_page_url = "http://localhost:4200/"
